services:
  ps3netsrv:
    image: ps3netsrv
    container_name: ps3netsrv

    environment:
      - PS3NETSRV_PORT=38008
      - SYNC_ROMM_PATH=true

    volumes:
      # Volume for RomM support
      - /romm/library/roms:/ps3netsrv/ROMM_LIBRARY:ro

      # Uncomment if you want use standard PS3NetSrv folder structure 
      # - ./ps3netsrv:/ps3netsrv:ro

    ports:
      - 38008:38008